### ISSUE TITLE
How can I run properly the example?

### ISSUE THREAD

**Issue by anjopater** [breejs/express-example#1]
Hi, great library! 

Just a question, how I can run the xample, I mean I need run separately `node index.js` and `node bree.js` ? because I tried run just `index.js`  and after that do a `POST`  request to `http://localhost:8080/book-ticket` giving it a body like this:

```
{
    "email": "xxxx@gmail.com",
    "start_time": "08/09/2020 13:30"
}
```

however it don't scheduled the email, it sent the email like `http://localhost:8080/send-email`

Meybe i´m doing a mistake, any way to run the example properly?

**Comment by niftylettuce** [comment]
Yes, you run `node index.js` and `node bree.js` separately at the same time.  I could rename `index.js` to `app.js`, but you are correct.

**Comment by niftylettuce** [comment]
@anjopater I have added a full working example for this repo at <https://github.com/breejs/express-example#example>.  Let me know if you need anything else.

![Screen Shot 2020-08-11 at 7 19 19 PM](https://user-images.githubusercontent.com/523141/89961545-991e4100-dc07-11ea-8057-8f97be21819a.png)
